const EVENTS=[
{id:1,region:"Киевская область",lat:50.45,lon:30.52,types:["hit","damage","injured"],status:"Подтверждено",text:"Сообщалось о повреждениях гражданской инфраструктуры и пострадавших.",source:"Reuters",url:"https://www.reuters.com/world/europe/russian-drone-barrage-kyiv-enters-fifth-day-disrupting-life-across-capital-2026-08-31/"},
{id:2,region:"Одесская область",lat:46.48,lon:30.72,types:["hit","damage"],status:"Подтверждено",text:"Сообщалось о повреждении гражданской инфраструктуры, включая терминал Nova Poshta.",source:"Reuters",url:"https://www.reuters.com/world/europe/russian-drone-barrage-kyiv-enters-fifth-day-disrupting-life-across-capital-2026-08-31/"},
{id:3,region:"Днепропетровская область",lat:48.46,lon:35.05,types:["hit","damage","injured"],status:"Подтверждено",text:"Сообщалось о повреждениях предприятий и инфраструктуры и раненых.",source:"Национальная полиция Украины",url:"https://npu.gov.ua/"},
{id:4,region:"Запорожская область",lat:47.84,lon:35.14,types:["hit","damage","injured","dead"],status:"Подтверждено",text:"Сообщалось о погибших, раненых и повреждениях гражданских объектов.",source:"Национальная полиция Украины",url:"https://npu.gov.ua/"},
{id:5,region:"Херсонская область",lat:46.64,lon:32.62,types:["hit","damage","injured"],status:"Подтверждено",text:"Сообщалось о повреждении гражданской инфраструктуры и пострадавших.",source:"Херсонская ОВА",url:"https://khoda.gov.ua/"},
{id:6,region:"Николаевская область",lat:46.97,lon:32.00,types:["hit","damage"],status:"Уточняется",text:"Регион фигурирует в сообщениях о последствиях ночной атаки; детали требуют дополнительной проверки.",source:"Открытые региональные сообщения",url:"https://www.google.com/search?q=Николаевская+область+31+августа+2026+атака"},
{id:7,region:"Харьковская область",lat:49.99,lon:36.23,types:["hit","damage"],status:"Уточняется",text:"Есть сообщения об атаках; отдельные эпизоды требуют проверки.",source:"Открытые региональные сообщения",url:"https://www.google.com/search?q=Харьковская+область+31+августа+2026+атака"},
{id:8,region:"Донецкая область",lat:48.30,lon:37.80,types:["hit","damage"],status:"Уточняется",text:"Есть сообщения о последствиях ударов; часть событий относится к продолжающимся боевым действиям.",source:"Открытые сообщения",url:"https://www.google.com/search?q=Донецкая+область+31+августа+2026+удары"},
{id:9,region:"Сумская область",lat:50.91,lon:34.80,types:["hit","damage"],status:"Уточняется",text:"Атаки/обстрелы подтверждаются, но не все сообщения можно однозначно отнести к одной волне.",source:"Открытые региональные сообщения",url:"https://www.google.com/search?q=Сумская+область+31+августа+2026+атака"}];